version: '3.1'
services:
 mysql:
  image: mysql:8.0
  restart: always
  volumes:
   - ./data:/usr/workspace
  ports:
   - 3306:3306
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: stockmarket
   MYSQL_USER: admin
   MYSQL_PASSWORD: adminuser
volumes:
 data: