#-----------------------------Global configs -----------------------------------#
server:
 port: 8082
 
## Spring DATASOURCE
spring:
 datasource:
  url: jdbc:mysql://e-stockmarket.cluster-cbb527yjemxm.ap-south-1.rds.amazonaws.com:3306/stockmarket   
  username: admin
  password: adminuser
#Hibernate
 jpa:
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  hibernate:
   ddl-auto: update