#-----------------------------Global configs -----------------------------------#
server:
 port: 8082

spring:
 data:
  cassandra:
   contact-points: 127.0.0.1
   local-datacenter: datacenter1
   keyspace-name: stockmarket
   username: cassandra
   password: cassandra
   port: 9042
